### ISSUE TITLE
x916 - Enhance cDNA Analysis on Visium QC page

### ISSUE THREAD

**Issue by BenTopping** [sanger/stan-client#202]
**User story**
As ARA (ilaria) I would a enhance the cDNA Analysis page on Visium QC to allow for either cDNA concentration or library concentration, called Visium Concentration 

**Who are the primary contacts for this story**
Ilaria

**Acceptance criteria**
To be considered successful the solution must allow:
Select from dropdown list either cDNA Concentration or library concentration, concentration unit = pg/ul
New: select a QC comment, from dropdown list (edited on config page) default no comment or blanket: Potential to work, Not recommended to proceed. Manditory. For each filled well on a 96 well plate. generally 4-8 wells 

would need to feature on release files. - new story
Katy to see current view and what needs adding - new story

**Comment by BenTopping** [comment]
@khelwood 
For core side:

**Op type changes**
- 'cDNA analysis' now becomes 'cDNA concentration' 
- Add 'Library concentration'

**Comments changes**
- There are already visiumQC comments for the 'sample processing' section but we need to add separate comments for concentrations in visiumQC (listed in the above description)

**SlotMeasurements**
- Slot measurements will now accept an optional commentId.

**Additional notes**
In the story description it states that the concentration unit needs to be pg/ul but im not sure where this needs specifying / adding. Maybe just in the label in the concentration field in client.

**Comment by khelwood** [comment]
@BenTopping I've made a core branch called `library`. Please check it seems to match the requirements.

**Comment by khelwood** [comment]
Also `static/x916_library.sql` in the stan-sql repo.
