### ISSUE TITLE
x932 - transfer samples to track and split the samples for Visium CytAssist

### ISSUE THREAD

**Issue by BenTopping** [sanger/stan-client#220]
**User story**
As TS (Katy) I would like to be able to select the state change at the 96 well plate conversion (currently Visium cDNA) and select whether the source is discarded/used or not, to allow us to track and split the samples in one 96 well plate onto another for Visium Cytassist workflow

**Who are the primary contacts for this story**
Katy T

**Dependencies**
x883

**Acceptance criteria**
Some data and measurements (such as perm times and stain type) that were recorded on the source labware need to be listed in the release data when the destination is released.

Rename Visium cDNA operation to "Transfer" (it will not be necessary to distinguish visium cdna ops from transfer ops for tracking purposes)

** reports might change/need amending

**Notes**
User can specify whether each source is left used, discarded, or active.
User can specify a bio state for each destination (cDNA, Probe, Library).
User can transfer into multiple destination plates (in one go).

**Comment by BenTopping** [comment]
@seenanair think this is your story? ^

**Comment by seenanair** [comment]
@KatyTudor @BenTopping Yes, I have changed the description

**Comment by KatyTudor** [comment]
@khelwood how tricky is it to add destination States for this at a later date? feature is working really well. ilaria is just thinking if there's any other states we need to add, is it just a ticket or a story?

**Comment by KatyTudor** [comment]
@khelwood excellent think we can release this then :-)
