### ISSUE TITLE
x800 File upload viewing

### ISSUE THREAD

**Issue by KatyTudor** [sanger/stan-client#226]
User story
As a TS (Katy) I would like to view the files uploaded in x808 on the history page, so users and customers can view and download the files

**Comment by KatyTudor** [comment]
@seenanair the files don't appearing to be appearing on the history page

**Comment by seenanair** [comment]
Ohh! I think I missed that link to be included. I will do it

**Comment by seenanair** [comment]
@KatyTudor  Do you have any preference for ‘files’ table column order  in history page ?

**Comment by KatyTudor** [comment]
@seenanair is it possible to download the files from the history page too? Otherwise the customers would need to log in and we need that feature to be for people not logged in. but keep the file manager page to be logged in users only?
