### ISSUE TITLE
x934 As TS (Katy), I want to select a Program when creating a new work number on the SGP Management page, because this will allow us to track/filter by program type now we are running requests across Sanger.

### ISSUE THREAD

**Issue by KatyTudor** [sanger/stan-client#237]
"To be a dropdown list edited on the config page: CellGen, CASM, HUMGen, SGP
Add to the work_view
Projects are not part of programs.
Program is mandatory for work numbers (needs backfilling for old ones). Info for patch is [here](https://docs.google.com/spreadsheets/d/1op2DSEEneTAvaDfgnTDWAx8T11jTBsALZt-uTRtzdEM/edit?usp=sharing)

**Comment by khelwood** [comment]
@KatyTudor 
Need programs for 
R&D17
R&D18
SGP63
SGP64

**Comment by KatyTudor** [comment]
@khelwood I have added these to the google sheet now, they were created after I made the list sorry, might need to revise it just as we release the feature

**Comment by KatyTudor** [comment]
@khelwood Can you also add PaM to the list sorry
