### ISSUE TITLE
x980 - As TS (Katy) I want to specify the work number when I release a piece of labware (one for each labware), for this to be stored against the release, and shown in the history

### ISSUE THREAD

**Issue by seenanair** [sanger/stan-client#292]
Have an option in the UI to apply one work number to all indicated labware. The default value should be the work number associated with the indicated labware
Work number is not mandatory for releases.

**Comment by seenanair** [comment]
Yes, I am half way through this on client side. But, of course we can discuss this maybe on tomorrow's standup?

**Comment by KatyTudor** [comment]
yes of course, just speaking with minal and want to check what direction the feature is going in as x980 an x982 are similar but different :-)

**Comment by KatyTudor** [comment]
@seenanair For this story we might need to release again completed work requests is it possible for the dropdown list for the worknumbers to be for all work request numbers?
sorry for not specifying that in the requirements

**Comment by seenanair** [comment]
The dropdown lists all work numbers( which includes the completed as well), if 'active' box is unchecked.

**Comment by KatyTudor** [comment]
Perfect thank you so much
