### ISSUE TITLE
x982—As TS (Katy), I want to choose labware for release by inputting a work number, because this will speed up releasing labware

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#299]
On the labware release page to have a filter by SGP to then pull up all the labware associated with that SGP 
able to unselect/remove from the table labware if not being released 

Notes:
medium - core and client

**Comment by KatyTudor** [comment]
@seenanair I can't seem to remove an item from the labware table so its not being released?

**Comment by seenanair** [comment]
Sorry, I thought all labware associated with an SGP need to be released in one go. I will add it.

**Comment by seenanair** [comment]
@khelwood I have added a new PR for this https://github.com/sanger/stan-client/pull/309
Please review when you get time
