### ISSUE TITLE
x946 Allow end users to create worknumbers/requests

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#321]
On main dashboard have a link to create request work, take them to the top half of the SGP management page for them to fill in (access when logged in as Enduser) and create an SGP (not to have access to editing the priorities).

All dropdown fields mandatory (except that the Omero project is optional for ""sample processing"" work type).
Only one field out of ""number of slides"", ""number of original"" etc. is required (but it is mandatory).
Message stating to complete RNAscope/IHC template for probes/antibody and fluorophore, and link to SGP FRED page, which they complete and upload on the file management page. Restrict to only upload to SGP's they've created

Story: Large

**Comment by seenanair** [comment]
1. Display **'Create work'** link in dashboard **only** if the user is logged in as 'End user'

2. Clicking on **Create work** link in dashboard navigates to SGP management page. Display only top half of the page.

3. Drop down fields in SGP management should behave as of now    - 'Omero project' field is optional
    -  One field out of 'Number of blocks', 'Number of slides' or 'Number of original samples' is mandatory
    - All other dropdown fields are mandatory
    
4. On succesfull creation of SGP number by  'End user' (by clicking 'Submit' ), display the message 'Please complete RNAscope/IHC template for probes/antibody and fluorophore' as well as a link to SGP FRED page
     
 5. In the 'File manager' page, if the user is logged in as 'End user' , then only list the SGP's created by the logged in 'end user'  (API required?) and allow file upload for those.

**Comment by KatyTudor** [comment]
This looks great, my only thought would be 1.1 can the link be viewable to all then if they click the link it gets you to log in? and takes you to the SGP management page?

**Comment by KatyTudor** [comment]
@mp20sanger can you check over the above too please? check we've not missed anything

**Comment by seenanair** [comment]
> This looks great, my only thought would be 1.1 can the link be viewable to all then if they click the link it gets you to log in? and takes you to the SGP management page?

That sounds good 👍

**Comment by khelwood** [comment]
@KatyTudor For this story do we need to allow the following:
1. End users can only upload files for work that they themselves created?
2. End users can update fields in work (status, numblocks etc.) that they created?

**Comment by KatyTudor** [comment]
@khelwood 

1. Yes, though that rule might come back and kick us in the bum
2. I don't think they need access to the table of work requests as they might then activate/change status or prioritisation, unless we can get them access to the table but not edit priority or status?!

**Comment by seenanair** [comment]
Ok, so I hope  for the time being it is ok to  keep the table of work requests not visible to enduser.

**Comment by seenanair** [comment]
@KatyTudor Just to confirm , I hope  this is Fred SGP page link  https://fred.wellcomegenomecampus.org/Interact/Pages/Content/Document.aspx?id=6817&SearchId=1829746&utm_source=interact&utm_medium=quick_search&utm_term=sgp+page

**Comment by KatyTudor** [comment]
@seenanair , sorry yes that's the correct link.

this feature is working nicely, but can we make the notice as bit clearer as it pops up with any of the requests created, can it say "If you have submitted a RNAScope/IHC request please complete the template for probes/Antibody and fluorophore here, and upload to STAN on the file management page linked to your request number”

**Comment by seenanair** [comment]
@KatyTudor uat is updated now. Please check when you get time

**Comment by KatyTudor** [comment]
@seenanair Harriet has tested the feature and it works nicely but she thought we may need more info on the assigned worknumber, to take note of their request number or they can search their request number and status on the main dashboard by filtering under requester/program/ worktype

**Comment by seenanair** [comment]
-What more info is needed on the assigned worknumber?
-Is it only required for end users?

An example of  usual confirmation message displayed after creation of SGP is as follows
**_"Assigned SGP162 (Hiplex RNAScope - 1 blocks) to project Adult healthy and eczema skin visium, Omero project KR_SMAN and program CASM using cost code S1743 with the work requester ao15"_**

**Comment by KatyTudor** [comment]
@seenanair its to follow on from the above to remind them to take note of their work request number:

"Assigned SGP162 (Hiplex RNAScope - 1 blocks) to project Adult healthy and eczema skin visium, Omero project KR_SMAN and program CASM using cost code S1743 with the work requester ao15
Please record your work request number for future reference, if you mislay this information you can find your request number on the home page by filtering by requester/program/worktype, etc."

does that read ok?

**Comment by KatyTudor** [comment]
@seenanair harriet has also asked if we can make the work request number larger/more prominent so it really stands out

**Comment by seenanair** [comment]
Ok, I will update the message and the work number more prominent

**Comment by seenanair** [comment]
@KatyTudor , @khelwood 

Please see the changed message. Please suggest any change in wordings if required

![Screenshot 2023-05-04 at 15 09 58](https://user-images.githubusercontent.com/55585488/236233655-b6691d4d-bed4-4340-a5d9-7c5d29bb999b.png)

**Comment by seenanair** [comment]
> thanks Seena sorry for the extra changes the teams only just getting back to me

Not a problem. Happy to get feedback 👍

**Comment by KatyTudor** [comment]
looks good to me, thanks for doing it so quickly

**Comment by seenanair** [comment]
Once  @khelwood reviews it, will merge to uat and let you know
