### ISSUE TITLE
x1056 As TS (Katy) I would like the visium concentration unit to be visible on the visium concentration table for confirmation in the lab

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#365]
pg/μL for both cDNA concentration and Library concentration

![Image](https://user-images.githubusercontent.com/111565178/254889627-97608b8b-9764-4c47-b21d-aa9dff225a3e.png)

**Comment by KatyTudor** [comment]
@sabrine33 can you make the unit pg/μL on the page as "pg/μL" not in capitals please? and use the "μ" symbol, so its accurate. Thanks
