### ISSUE TITLE
x1034—As a developer (Seena), I would like to understand the work needed to upgrade to React 18

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#369]
We need to understand the work needed to upgrade from React 17 to React 18

**Comment by seenanair** [comment]
Following are the activities required to upgrade to React 18

- Support for Prompt 
- Upgrade to  react-router v6.0
- Upgrade to React 18
- Upgrade following libraries
   - react-dom
   - cypress
   - testing-library/cypress
   - jest
   - xState
   - Formik and yup
