### ISSUE TITLE
x1066 As PO (Minal), I want horizontal scroll bars at the top of the tables on the dashboards, history page, search page and SGP management page for ease of use

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#389]

**Comment by KatyTudor** [comment]
@sabrine33 this is working great on the history, search and management pages but the scroll bar is on the bottom of the table on the dashboard pages, can you update these as well please?

**Comment by sabrine33** [comment]
Thank you @KatyTudor for the feedback, the top scroll bar is present at my end in the dashboard  page (Summary dashboard page) or may be we are looking into different pages; could you please provide more details about the pages that you are looking into, thanks
<img width="782" alt="Screenshot 2023-09-12 at 08 49 19" src="https://github.com/sanger/stan-client/assets/139128026/6da125f6-27dc-412d-86ab-0b6ef3d09f3b">

**Comment by KatyTudor** [comment]
@sabrine33 I think on the test summary dashboard I see theres not a scroll bar o nthe top:



![Image](https://github.com/sanger/stan-client/assets/111565178/796c0d59-c626-436f-a717-8fc688a433cf)


is my screen is too big and the scroll isn't needed?

The other dashboard is the main dashboard you come to on the home page:



![Image](https://github.com/sanger/stan-client/assets/111565178/40cecca0-d9af-483c-9dc9-f5d98ee0181a)

**Comment by sabrine33** [comment]
@KatyTudor , yes, so basically the scrolling bars are only present when they are needed, in the case of the test summary dashboard, you need to minimise the width of your window to make it show up. Also, I think I missed the main dashboard page; I will update it now. Thanks.
