### ISSUE TITLE
x1088 v2.29—As ARA (Jasmine) I want to record if the RNA analysis is performed on the Bioanalyser or Tapestation, for billings and  accurate recording

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#428]
"all tubes (labware) for the same operation on the same machine type

Dropdown list for machines

Column added to RNA_Analysis_view"

**Comment by khelwood** [comment]
@sabrine33 Are you going to use [Equipment](https://github.com/sanger/stan-core/blob/devel/src/main/java/uk/ac/sanger/sccp/stan/model/Equipment.java) for this?
