### ISSUE TITLE
x1095 2.30.0—As ARA (Jasmine), I want the FFPE processing (Paraffin Processing) operation to associate the medium paraffin with the sample

### ISSUE THREAD

**Issue by seenanair** [sanger/stan-client#446]
Labwork -> original sample -> FFPE processing

(Automatically record that the samples have the medium paraffin applied)

On summary on page, state that samples are now embedded in Paraffin medium

**Comment by khelwood** [comment]
Core branch: [ffpe_medium](https://github.com/sanger/stan-core/pull/285)
