### ISSUE TITLE
x1101 2.30.0—As TS (Katy), I want to see the fixative and medium for the labware on the labware details page, to allow users to double check sample preparation for the labware they are using

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#450]

**Comment by khelwood** [comment]
Generally expect all the samples in an item of labware to have the same fixative and medium.

**Comment by KatyTudor** [comment]
@sabrine33 sorry if I am being daft were is this appearing? 

![Image](https://github.com/sanger/stan-client/assets/111565178/a9292e92-6878-4cd6-9620-e6499d213298)

I can't see it on the labware details page

**Comment by sabrine33** [comment]
Hi @KatyTudor , I am not unsure why it is not being displayed on your end. The 'Medium' and 'Fixative' information should be shown within the 'Labware Details' table, located in the top right-hand corner. However, please note that this information is only added when there is tissue information associated with the samples. We are currently checking the first sample within the first slot in the labware for this data.

<img width="418" alt="Screenshot 2023-11-01 at 10 47 09" src="https://github.com/sanger/stan-client/assets/139128026/ec00d748-162e-40fb-9211-6bf53c52a267">

**Comment by khelwood** [comment]
@KatyTudor Presumably because the first labware didn't have any tissue in its first slot.

**Comment by KatyTudor** [comment]
@sabrine33 @khelwood or is it safer to put the information on the samples table on the page?

**Comment by sabrine33** [comment]
@KatyTudor, In my opinion, the decision depends on the specific use case. If all the samples within the same labware share the same medium and fixative, incorporating this information into the labware details would provide better visibility and eliminate redundant data in the sample tables.

**Comment by sabrine33** [comment]
We agreed to display the fixative and medium information within the sample table, to cover some edge cases where users might have used different fixatives/mediums within the same labware.

**Comment by khelwood** [comment]
@KatyTudor This has been updated on UAT.

**Comment by KatyTudor** [comment]
thanks guys for the changes, that's working great
