### ISSUE TITLE
x1092— v2.31 As ARA (Jasmine), I want Sample Processing renamed "Labware generation", Block Processing renamed "Block", and Pot Processing renamed "Pot"

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#456]

**Comment by KatyTudor** [comment]
note: Katy Needs to update billing reports etc. so can we release the beginning of a month please

**Comment by KatyTudor** [comment]
On the title page it still reads "Original Sample Processing" can this be changed to "Labware generation" please?



![Image](https://github.com/sanger/stan-client/assets/111565178/12ce3541-1ddb-4ebe-8404-f56b60944a76)


then as you select the labware to be created the comments are titled "Processing comments" could these be changes to Labware generation comments

And I spotted that the sample processing comments under the labwork> original sample has changed to Labware generation comments can these be changed back to Sample processing comments please? as these can be applied to any step in the sample processing steps



![Image](https://github.com/sanger/stan-client/assets/111565178/501f4c5b-92b8-48ae-b805-d91af8542a27)

**Comment by khelwood** [comment]
Please make any changes on a branch from the current release candidate (`2.31.1`) so that it can be included in the next release.
