### ISSUE TITLE
x1116 (client) As TS (Katy) I would like any user to be able to un-destroy and un-discard Labware

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#474]
admin menu on STAN

**Comment by KatyTudor** [comment]
@sabrine33 when testing this out, the operation is asking to provide a comment/reason why its reactivated, but I can't find on the config page how to add these comments/reasons, can you help?

**Comment by KatyTudor** [comment]
@sabrine33 @khelwood some of the team are coming up with the below error:



![Image](https://github.com/sanger/stan-client/assets/111565178/0bc3c7d5-a4e9-45d7-95ef-b55b13b24bed)

but the labware is destoryed:



![Image](https://github.com/sanger/stan-client/assets/111565178/f267ea9d-db2c-407e-aba8-c23b76e15d2c)

**Comment by sabrine33** [comment]
Thank you I will have a look

**Comment by khelwood** [comment]
If this requires a fix, please make changes on a new branch from the current production release.
