### ISSUE TITLE
x1117 v2.33—As ARA (Harriet), I want to upload multiple files at one time on the file uploader page, to speed up the workflow

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#487]
Select one work number.
Select multiple files.
Press upload.
Client uploads them to core (sequentially?)

**Comment by KatyTudor** [comment]
@khelwood @seenanair @sabrine33 I am getting an error message on testing this but it doesn't say what the error is?



![Image](https://github.com/sanger/stan-client/assets/111565178/df274d79-093c-42e6-9ed4-5a6a18a098bc)

**Comment by seenanair** [comment]
@KatyTudor When I tried in UAT, it seems to be working ok. I will try with some more files 

https://github.com/sanger/stan-client/assets/55585488/0f591719-48eb-4692-b8eb-3b2cb0f87733

**Comment by khelwood** [comment]
When we get errors with the file upload/download it's often because of the network file directory (where we store the files). I remounted the directory on stan-uat this morning and now it seems to be working.

**Comment by KatyTudor** [comment]
working fine now thanks
