### ISSUE TITLE
x1125 client—As ARA (Harriet) I want to record library amplification/dual index plate/Transfer/cycle number for visium cytassist workflows in one page, to reduce clicks and errors happening in the lab

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#528]
New page Library Preparation - in Visium menu - description to state Visium "Library Amplification and Generation"

Select SGP number
Scan in source labware, stays active (drop-down list - selected by user, default as empty).

1to1 transfer the destination labware (option to scan in destination labware (already in use) or create a new 96 well plate labware) (like visium transfer operation)
Destination labware state to be select-able from dropdown list (default as empty)

Scan in Dual index plate (source side) – allocate one per well in the output labware. As per dual index plate operation, links in with the well data and tag information needed on the release file
(like dual index plate operation)

Mandatory that you scan in both source labware and scan in dual index plate for operation to complete

Be able record Cycle number (not CQ value due to new story coming - we will need to enhance this feature to allow pulling up of recorded CQ value for sample) per well on the destination plate (like visium QC - amplification operation) - only for wells you make the transfer for

Not to affect current views for billing and reporting, but will need to check when operation is on UAT

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 Jasmine has tested this and it works well but she did get the following message clicking ‘return home’ on the ‘operation complete’ pop up. In not sure what it thinks is unsaved. 


![Image](https://github.com/sanger/stan-client/assets/111565178/4d177a5b-375f-4116-a672-c45410a013aa)

**Comment by sabrine33** [comment]
@KatyTudor , It seems that she attempted to leave the page before clicking on the buttons in the 'operation complete' pop-up. Was she testing it on a tablet? Even an accidental swipe to the left or right may trigger it.

**Comment by KatyTudor** [comment]
@sabrine33 she said she had clicked save/complete then from the "operation complete" pop up when she pressed reset or home it came up with the other pop up with unsaved changes

**Comment by sabrine33** [comment]
@KatyTudor, okay thank you for the feedback, I will have a look

**Comment by KatyTudor** [comment]
@sabrine33 Harriet has also tested and there is no option to print the new destination plate(s) labels, can you add this please? thanks
