### ISSUE TITLE
RT#795768 v2.36 Bug related to information in storage UI

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#533]
Some information is apparently missing from the UI for labware in storage.
The problems are described in [the RT ticket](https://rt.sanger.ac.uk/SelfService/Display.html?id=795768).
It might be multiple issues that could be separated into bugs/feature requests.

**Comment by seenanair** [comment]
@KatyTudor @khelwood,  Following is what I understood from RT ticket.  Would you please check if it is correct?

There are two issues 
1) Sample information is missing in table for the selected location. External Id, Donor, Spatial location, Replicate fields are empty ( only displays Address, Barcode and SGP Number column values)
2) For labware with multiple samples, externalID field in table displays only one

**Comment by KatyTudor** [comment]
@seenanair I can't see the ticket I don't have permission, but from what I heard from Jasmine, yes that was the main two issues

**Comment by khelwood** [comment]
Yes those seem to be the issues. @seenanair I've added you to the ticket so you should be able to access it.

**Comment by seenanair** [comment]
@KatyTudor , @khelwood  The reason behind both issues is, on the client side it is only checking the first sample in the first slot, which is not the case always. So , ideally we need to display all samples across all slots, I hope. 

So, to confirm 
 - Is it ok to  display the values of the same field across all samples in a labware  as comma separated values in the table? 
   For e.g if labware STAN-3111  has got 'sample 1', 'sample 2' (in slot A1) and 'sample 3' (in slot A2) with external IDs EXT1, EXT2, EXT3 respectively, then the 'External Id' field in table will display EXT1, EXT2, EXT3

**Comment by khelwood** [comment]
If there are three samples on the labware, but they all have the same (let's say) external id, should it show the external id once or three times?

**Comment by KatyTudor** [comment]
@seenanair @khelwood I think if they have the same external ID then just show it once but if they have different IDs to show them all, if that is possible?

**Comment by KatyTudor** [comment]
@seenanair @khelwood I am only getting one ID coming up and for this labware there are four different external IDs



![Image](https://github.com/sanger/stan-client/assets/111565178/66561a51-d088-46fd-955b-c74327f527cb)

**Comment by seenanair** [comment]
@KatyTudor Oh, ok. I will look into it

**Comment by seenanair** [comment]
@KatyTudor  The fix is in uat now. Please have a look when you get time.
