### ISSUE TITLE
x1143 v2.37.1—As ARA (Hon Man) I would like the flag on a labware more visible on the history page so you are not searching down the page to see if there is a flag

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#550]
at the top of the history page, above or below the files for SGP, can we have a flag icon that takes you to the labware details page to view the flag, needs to be visible by users not logged in

For all search terms

Small

**Comment by khelwood** [comment]
When stan-client has loaded some history, if there are any flags in the history, it should show a box above the history table listing the flagged labware.

**Comment by KatyTudor** [comment]
@seenanair can we have this on the history page not the labware details page, the flag links for the labware need to take the person to the labware details page to see the flag description

**Comment by khelwood** [comment]
For this history page https://stan-uat.psd.sanger.ac.uk/history?eventType=Flag%20labware the core gives a list of flaggedBarcodes
```
"flaggedBarcodes": [
        "STAN-0001F",
        "STAN-000E2",
        "STAN-00352",
        "STAN-019B9",
        "STAN-02077",
        "STAN-15B25",
        "STAN-16F0A",
        "STAN-1B49D"
      ]
```
but the flagged-labware-box does not appear on the history page.
