### ISSUE TITLE
x1167 (client)—As TS (Katy), I want to use n/a for life stage in all registration pages to accommodate organoid/cell culture work

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#568]

**Comment by KatyTudor** [comment]
@sabrine33 if possible that would be great thanks

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 Harriet tested the file upload and left that column blank and it allowed the upload to happen without that information filled. can you change it so the that column needs to be filled in please? works on the manual version as you have to select one/adult is default

**Comment by KatyTudor** [comment]
@sabrine33 @khelwood when its upload the display on the lab-ware details page has it as "N/a" can I be picky and get it to display as either "N/A" or "n/a" please:



![Image](https://github.com/sanger/stan-client/assets/111565178/589b7b82-d3f5-4a6c-baff-01d644b4b329)

**Comment by sabrine33** [comment]
@KatyTudor, I would if that is the value specified in the file, the client should display 'N/A', if any exist.

**Comment by KatyTudor** [comment]
@sabrine33 I think when Harriet tested it she also tested the manual registration and that gave the same N/a. I will be updating the form to be dropdown and only allow N/A



![Image](https://github.com/sanger/stan-client/assets/111565178/30ab8f3b-d48c-439a-bcca-29cc703203d0)
