### ISSUE TITLE
x1148 As TS (Katy) I would to increase the Probe hybridisation lot number character length to 25 and change the default time to the current time when you scan in labware, to streamline things in the lab more

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#571]
Katy to describe the issues - may be possible bug

Katy's response 13/3/24 - default time to be when you scan in the labware for that operation please - currently time varies by hours earlier possible when you logged into STAN?!

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 Jasmine has tested this and got an "error still appears saying ‘Lot number should have a maximum length of 20 characters’
              Also, I sometimes am getting this error when putting in an earlier time for the ‘start time’ e.g. at 11:51 and I tried to put in a time of 11:48."


![Image](https://github.com/sanger/stan-client/assets/111565178/68a1e082-f162-473f-a745-6f3fc085b504)

**Comment by sabrine33** [comment]
@KatyTudor , I will double check the lot length for you, the time error is generated by the core, cc @khelwood

**Comment by khelwood** [comment]
@KatyTudor The "date is too early" error happens when you try and use a timestamp that is before the source labware was created.

**Comment by KatyTudor** [comment]
@khelwood thanks that makes sense

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 I just got this error but not sure what it means?



![Image](https://github.com/sanger/stan-client/assets/111565178/b4055320-e8e8-498b-964e-53cb7e28f523)

**Comment by khelwood** [comment]
@KatyTudor I think that's because I neglected to expand the lot number column in the database. Should be fixed now.

**Comment by KatyTudor** [comment]
@khelwood its working great now thanks
