### ISSUE TITLE
x1184 (client)—Cell segmentation

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#623]
New feature under Xenium menu called "Cell Segmentation".
Happens in place.
Work number for each labware. Be able to apply all or individual barcodes.
User-specified timestamp for each labware. Be able to apply all or individual barcodes.
User-selected "Segmentation panel" from dropdown list (set up via config page).
User-selected comment (set up via config page). Be able to apply all or individual barcodes.

**Comment by KatyTudor** [comment]
@sabrine33 can you set it so the comments aren't mandatory please?
