### ISSUE TITLE
x1185 (client)—As TAS (Katy), I want to record a new operation called Cell segmentation Xenium QC, to document the end time for the cell segmentation process

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#626]
New feature under Xenium menu: "Cell Segmentation QC"

Scan multiple labware for operation in place. Labware should have had _Cell Segmentation_ op recorded on them already.
Select SGP number (drop down). Be able to apply to all or to individual barcodes.
Option to input timestamp as per other xenium features. Be able to apply to all or to individual barcodes. The time should be in the past and after the cell segmentation operation time.

Select comment(s) (multiple for each labware). Be able to apply to all or individual labware.

**Comment by KatyTudor** [comment]
@sabrine33 can you set it so the comments aren't mandatory please?
