### ISSUE TITLE
Set the Comments field as optional for Cell Segmentation and Cell Segmentation QC

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#644]

**Comment by KatyTudor** [comment]
@sabrine33 @khelwood I am still getting a message saying the comment is required


![Image](https://github.com/sanger/stan-client/assets/111565178/a4b58efa-7094-4ba9-8af0-ee0cd2eaec82)

**Comment by khelwood** [comment]
@KatyTudor I've updated UAT. Is it still a problem?

**Comment by KatyTudor** [comment]
@khelwood working great now thanks
