### ISSUE TITLE
x1189 client—As TS (Katy), I want to upload/deal with the xenium metrics summary to Stan to pull the information into a view for reporting

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#671]
In the xenium lab menu, new operation called Xenium Metrics.

* Select SGP number
* Scan in labware
  - pulls up the Region of interest already to the linked labware in STAN (as Defined in the Xenium analyser operation)
* Select the Region of interest for file upload
* Upload file(s)
Do not need to view metric in Stan, just pull into a view called `xenium_metrics`
O
[File example](https://github.com/sanger/stan-core/files/15262926/metrics_summary.csv)

Metric summary sheet from Xenium Analyser is [here](https://docs.google.com/spreadsheets/d/1e_1jr-oRDLkPaFU5LsrH8Gol_lkbfzPpKXT4EbkgqNQ/edit?usp=sharing)

* Read CSV file, store columns and single-data-row as key/values.
* Write view assuming that the rows are consistent.
* The view shows all the data as if a concatenation of the data rows from each file.
* Scan in one labware
  - Whichever is easier: select one region of interest, upload one file
  - Or specify a file each for multiple regions of interest and upload them all
* If you upload a new file for some labware/roi that already has a file, the information is replaced

NB Multiple samples (in possibly multiple slots) may share the same region of address, so the file uploaded for that region would apply to all of them.

**Comment by KatyTudor** [comment]
@sabrine33 on the labwork menu for Xenium can we arrange the operations in the below order please? or is that a separate story?

Cell segmentation
Cell segmentation QC
Xenium analyser
Xenium QC
Xenium Metrics

**Comment by sabrine33** [comment]
@KatyTudor , I will create a story a do it

**Comment by KatyTudor** [comment]
@sabrine33 thanks

**Comment by KatyTudor** [comment]
@sabrine33 this is looking great. I don't know what I haven't done but it won't let me save?



![Image](https://github.com/sanger/stan-client/assets/111565178/28dc5682-ad65-4fff-a1ee-cd992dbe0934)

**Comment by khelwood** [comment]
@KatyTudor Can you send me the specific csv file you used here please?

**Comment by KatyTudor** [comment]
[metrics_summary.csv](https://github.com/sanger/stan-client/files/15467473/metrics_summary.csv)
@khelwood there was one file per region but all named the same file name. attached is one of the files
