### ISSUE TITLE
x1198 client—As ARA (Jasmine) I want to assign a comment on the Xenium QC per Region of Interest (as defined in the Xenium Analyser step) not the whole slide, for accurate tracking and reporting

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#672]
Still have option to apply all.
Comments not mandatory

This is for the case where there are different samples in different sections; so we can store comments as being linked to specific samples (which are in that region of interest).

Allow user to select zero, one or more comments for each region of interest.

Have option to apply a comment to all regions.

Keep existing comment-on-all capability.

Update release file if necessary to convey new information.
Update history if necessary to convey new information.

**Comment by khelwood** [comment]
@sabrine33 This is how I'm planning to write the graphql. I'm presuming that the client will look up which samples are in which regions of interest in the labware:

```graphql
"""A comment on a particular sample in a particular slot."""
input QCSampleComment {
    """The address of the slot."""
    address: Address!
    """The ID of the sample."""
    sampleId: Int!
    """The ID of the comment."""
    commentId: Int!
}

"""Labware to be QC'd with comments and a completion time."""
input QCLabware {
    """The barcode of the labware."""
    barcode: String!
    """The work number to link to the operation."""
    workNumber: String!
    """The time at which the process was completed."""
    completion: Timestamp
    """Zero or more comments applied to this labware in this operation."""
    comments: [Int!]!
    """Zero or more comments on individual samples in particular slots."""
    sampleComments: [QCSampleComment!]
}

"""Request to record QC and completion time for one or more labware."""
input QCLabwareRequest {
    """The name of the operation to record."""
    operationType: String!
    """The specifications of labware to QC."""
    labware: [QCLabware!]!
}
```

**Comment by sabrine33** [comment]
@khelwood , Thanks, this looks okay. Should we add a new query to retrieve the regions of interest related to a labware?

**Comment by khelwood** [comment]
@sabrine33 Yes you're right. I'll add that too.

**Comment by khelwood** [comment]
@sabrine33  Something like this:
```graphql
"""Info about a region of interest."""
type RegionData {
    """The address of a slot."""
    address: Address!
    """The id of a sample."""
    sampleId: Int!
    """The region of the sample in the slot."""
    region: String!
}

"""Region of interest data about a piece labware."""
type LabwareRegionData {
    barcode: String!
    regionData: [RegionData!]!
}


Query:
    """Get regions of interest in the indicated labware."""
    regionsOfInterest(barcodes: [String!]!): [LabwareRegionData!]!
```

**Comment by khelwood** [comment]
@sabrine33 Actually I've noticed there is a query already:
```graphql
    """Gets the sample positions (if any) specified in a particular item of labware."""
    samplePositions(labwareBarcode: String!): [SamplePosition!]!
```
Is this one enough?

**Comment by KatyTudor** [comment]
@sabrine33 this is working nice but I don't think we need both apply to all comments



![Image](https://github.com/sanger/stan-client/assets/111565178/b8559d44-9597-45c3-9c68-c5f383f55b4d)

**Comment by sabrine33** [comment]
The first select "comments", are the selected comments related to the labware, (the old select - as we agreed to leave it). The second select "Apply to all"  is to apply comments to all the samples.

**Comment by KatyTudor** [comment]
@sabrine33 ah yes thanks for explaining

**Comment by KatyTudor** [comment]
@sabrine can the sample ID be the external ID sorry I just realised what that column was
then similar to the metric operation can the comment be per region. so have the columns region, slot, external ID, comment. so the below would only need 3 comments due to the three regions, and sort by slot address A's at the top


![Image](https://github.com/sanger/stan-client/assets/111565178/85cf2765-61a3-42cc-a89b-1c524df2b25f)

**Comment by sabrine33** [comment]
@khelwood following katy's comment, are we keeping the request as it is, or should we link the comment to the roi (instead of sampleid and address)?

**Comment by sabrine33** [comment]
@KatyTudor in the metric table columns are: roi, sampleId and address (grouped by roi), would you like to have roi, address and externalId (grouped by roi) in both pages (metrics and QC)?

**Comment by khelwood** [comment]
@sabrine33 It looks to me like the request will work OK as is, if the client already knows what sample are linked to what regions.

**Comment by KatyTudor** [comment]
@sabrine yes please, the same for both they need to be external ID not sampleId. the be ROI, External Id and address for column order

**Comment by sabrine33** [comment]
@khelwood is that possbile that Roi type, so it contains the external id? if that I can obtain it from the scanned labware

**Comment by khelwood** [comment]
@sabrine33 You mean this type?
```
"""A region of interest for a sample in an operation."""
type Roi {
    """The id of the slot."""
    slotId: Int!
    """The address of the slot."""
    address: Address!
    """The id of the sample."""
    sampleId: Int!
    """The id of the operation in which the ROI was recorded."""
    operationId: Int!
    """The description of the region of interest."""
    roi: String!
}
```

**Comment by sabrine33** [comment]
yes

**Comment by khelwood** [comment]
Maybe it would make sense to have it like this:
```
"""A region of interest for a sample in an operation."""
type Roi {
    """The id of the slot."""
    slotId: Int!
    """The address of the slot."""
    address: Address!
    """The sample."""
    sample: Sample!
    """The id of the operation in which the ROI was recorded."""
    operationId: Int!
    """The description of the region of interest."""
    roi: String!
}
```
then you can specify the `externalName` in the request as a field you want.
