### ISSUE TITLE
v2.44: RT#803875 Stan bug: Error when removing labware from the section confirmation screen

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#689]
![Image](https://github.com/sanger/stan-client/assets/14000840/6f3130f9-25cc-4055-af1c-5662b675e7d3)

**Comment by sabrine33** [comment]
@KatyTudor, I have been testing the deletion of labware from the section confirmation page, and it works fine on my end and on UAT. However, I found a bug when the user tries to mark a section as unused. I am working on fixing this.
Could you please confirm, the behaviour.

**Comment by KatyTudor** [comment]
@sabrine33 we were sectioning and went through planning and onto the confirmation page, when we tried to remove the tubes as we didn't end up taking any sections for tubes, we got the error, and it diverted us to try again which then took us to the blank confirmation page. which we scanned in the tubes for and them the same thing happened

**Comment by sabrine33** [comment]
apologies, I missed out the fact that we need to update the section number after deleting a section.
Question about the second screenshot: did you follow the same steps (delete labware(s), .. )before saving?

**Comment by KatyTudor** [comment]
@sabrine33 thanks Sabrine. Yes for the second screenshot I followed the same steps and deleted the unwanted labware then saved and got that error

**Comment by KatyTudor** [comment]
@sabrine33 has this been updated on UAT?
