### ISSUE TITLE
v2.44: x1203—As ARA (Ben) I want a new labware type called "8 strip tube" to reflect the visium workflow and releasing correct data

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#693]
label to be the same as 96 well plate for now then link to new printer if/when

labware to be active in all the visium operational pages option to select either 96 well plate or  8 strip tube (might need other stories to update these operations)

8 rows, 1 column

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 labware in the visium operations are still only showing the 96 well plate labware, for the story/labware we will need to be able to select either the 96 well plate as the original or an 8 strip tube labware

**Comment by sabrine33** [comment]
@KatyTudor , are you expecting the user to mix between labware types (2 strip tube and well plate) on the visium transfer. (destination labware using the add plate fct)

**Comment by KatyTudor** [comment]
@sabrine33 yes please

**Comment by KatyTudor** [comment]
@sabrine33 and also for the Library Amplification and Generation operation

**Comment by sabrine33** [comment]
There is no (+Add Plate) fct in the Library Amplification and Generation operation, currently the user can only select the type of plate (96 or 8 strip) or scan. 
If you would like to add the "Add Plate" fct, we can do in a different story

**Comment by KatyTudor** [comment]
@sabrine33 that would be great thank you, if you can add that option in

**Comment by sabrine33** [comment]
@KatyTudor, okay, let is add this to the backlog

**Comment by KatyTudor** [comment]
@sabrine33 I have add a story to the top of the backlog

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 Harriet has tested this out and on the transfer page got this error: 

![Image](https://github.com/sanger/stan-client/assets/111565178/2c0578e4-9cc4-498a-9077-b7cdb9266120)

**Comment by khelwood** [comment]
@KatyTudor It looks like the name was slightly different in the database. It should be fixed now.

**Comment by KatyTudor** [comment]
@khelwood its working nicely now. I'll just wait for feedback from the team who will test the whole process :-)
