### ISSUE TITLE
v2.44: RT#803875 - Updating section numbers after deletion

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#705]
More details here: https://github.com/sanger/stan-client/issues/689

**Comment by sabrine33** [comment]
Hi @KatyTudor , thank you for testing it,  the recent changes shouldn't be impacting the store functionality.
Also, I just conducted a test on UAT using STAN-1C2ED to create 3 new tubes through the section confirmation operation, and I was able to store them successfully.

From the screenshot provided, it appears that the system it is failing to store one specific labware. Could you confirm if this is the labware you just created within the section confirmation process? Additionally, I noticed that its details are missing from the table.

**Comment by KatyTudor** [comment]
@sabrine33 sorry for the delay. the screenshot is from testing the deleting of labware, I created the labware on the planning then at confirmation I deleted 1 tube, the section numbering was adjusted after deleting, but when I can to store the labware the deleted/discarded labware was in the list to be stored

**Comment by sabrine33** [comment]
@KatyTudor, Should discarded sections or deleted labware in the section confirmation page be present on the print labels page?

**Comment by KatyTudor** [comment]
@sabrine33 no they shouldn't

**Comment by KatyTudor** [comment]
@sabrine33 the error is still occuring, deleted tubes are still available to print (first image), and then appear on the "awaiting storage" (second image) and then when I try to store i get the error (last image):


![Image](https://github.com/sanger/stan-client/assets/111565178/879753b9-2ed1-4304-8de4-90cc52eef50d)



![Image](https://github.com/sanger/stan-client/assets/111565178/b0b470d7-73f4-4267-952e-a15315df3a46)



![Image](https://github.com/sanger/stan-client/assets/111565178/7f4b6a1f-6bc1-4738-83ad-071a5ff42ffd)

**Comment by sabrine33** [comment]
@KatyTudor apologies for the confusion, this is does not seem to be deployed yet on UAT.

**Comment by KatyTudor** [comment]
@sabrine33 no worries let me know once its updated and I can test
