### ISSUE TITLE
RT#805360 Stan UI problem: Scrolling alters selected values

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#709]
[RT#805360](https://rt.sanger.ac.uk/SelfService/Display.html?id=805360)

> On the sectioning planning page, when we select the Section Thickness bar and scroll up or down the number will automatically increase or decrease, leading to mistakes in the data entry.

**Comment by sabrine33** [comment]
This behaviour applies to fields (inputs) of type number. I
