### ISSUE TITLE
x1216 - As TS (Katy) I would like to add a date sectioned to the section registration page, so we can process sldies within the recommended limit of the protocols

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#715]
"On Manual entry to appear under the External barcode

To appear in the details column on the history page

Need to add column to the file upload registration

Appear on the release file in date sectioned column"

**Comment by sabrine33** [comment]
@Katy, Is the sectioned date related to the labware or to the slot? ie, for the same labware, when the user adds a new slot, is it required to enter a new sectioning date

**Comment by KatyTudor** [comment]
@sabrine33 it should be the same for all sections on a labware, but probably be safer to do it per slot on a labware

**Comment by sabrine33** [comment]
> @sabrine33 it should be the same for all sections on a labware, but probably be safer to do it per slot on a labware

If we are adding it per slot, better to add the sectioned input date within the section information (not after the barcode as requested), what do you think @KatyTudor

**Comment by KatyTudor** [comment]
@sabrine33 @khelwood I have attached the new request form with the new format because of this story, i.e. with Date sectioned column added

[SGP Xenium Request Form V3.xlsx](https://github.com/user-attachments/files/16082771/SGP.Xenium.Request.Form.V3.xlsx)
