### ISSUE TITLE
x1221 As ARA (Harriet) I would like to record the main peak size in addition to the concentration on the Visium QC concentration operation

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#725]

**Comment by khelwood** [comment]
New measurements:
* _Minimum size_
* _Maximum size_
* _Main peak size_

Each measurement value should be a positive integer.

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 this is working fine but Harriet said that recording the Min size and max size is tricky. Not on STAN but depending on how the sample is, i.e. just whether a peak is beyond threshold. shes now asking to change it to main peak size and average size for the library. Or should we release what we have done and then change it?

**Comment by khelwood** [comment]
@KatyTudor Probably best to change it before the release. If we release it and then change it, we'll have an anomalous group that has different measurements recorded to anything else.
Can you spell out the new requirements please?

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 can we change it to average size and peak size for the library concentration (so only two columns), and  remove the min and max size. 
for cDNA concentration to remove min and max and just have average size

**Comment by khelwood** [comment]
@KatyTudor Hopefully that change is up on UAT now

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 thanks for making the changes so quickly thats working great. I assume when release the view will have the new columns on?

**Comment by khelwood** [comment]
@KatyTudor You mean the `visium_concentration_view`? You want the new size measurements as columns in that? or somewhere else?

**Comment by khelwood** [comment]
@KatyTudor OK the UAT view has been updated.
