### ISSUE TITLE
RT#806599—Stan bug: DV200 value not being sent

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#728]
[RT#806599](https://rt.sanger.ac.uk/Ticket/Display.html?id=806599)

It looks like the client is sending an RNA analysis request with blank DV200 values, even when the fields are filled in on the page. I don't know if this happens consistently or under some particular circumstances.

**Comment by sabrine33** [comment]
It seems this issue only occurs when the user selects a different type (Range), enters the values, and then updates the type to "Single". The values are still correctly visible to the user but are not being sent to the server, which explains the error.
