### ISSUE TITLE
x1233—As ARA (Jasmine), I want the costings of the probe hybridisation Xenium to be changed to "probe costing" to distinguish them from kit costings.

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#742]
_Also_: Kit costing—on operational pages it is listed as _labware costing_; change that to _kit costing_

**Comment by KatyTudor** [comment]
@khelwood on the Probe hybri view can you change the costings to Probe costings? the kits costings is correct already

**Comment by khelwood** [comment]
@KatyTudor OK I've updated the probe hybrid view on Stan UAT.
