### ISSUE TITLE
RT#810186—Stan bug in Xenium Hybridisation step

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#754]
[RT#810186](https://rt.sanger.ac.uk/Ticket/Display.html?id=810186)

When we select add all in the Hybridisation section of Stan it produces these extra lines that aren't needed. 

This has happened consistently across three different attempts. 

![Image](https://github.com/user-attachments/assets/3be36869-b0ac-4122-a4b7-f61d32cda435)

**Comment by sabrine33** [comment]
This is a should be resolved by this : https://github.com/orgs/sanger/projects/9/views/2?pane=issue&itemId=83766692&issue=sanger%7Cstan-client%7C780
