### ISSUE TITLE
x1238 client—As TS (Katy), I want to add a decoding consumables lot number to the Xenium Analyser operation, to help move away from Excel lot tracking

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#764]
* Lot is 6 digits
* One per labware

**Comment by KatyTudor** [comment]
@sabrine33 @khelwood can you move the box to the analyser details part of the page? as ti would be the same lot number for the run /both slides

![Image](https://github.com/user-attachments/assets/ed667ae8-67b1-4c0e-bc78-25028dbfa4fa)

**Comment by sabrine33** [comment]
@KatyTudor, yes, sure. I added it there since the story specifies "per labware." Do you want it to behave like the SGP number field and populate the labware entries upon change?

**Comment by KatyTudor** [comment]
@sabrine33 sorry yes its per run not per labware
