### ISSUE TITLE
x1240 client—As ARA (Hon Man) I want to select an LP number (dropdown list - up to LP20) on the cytassist operation page, to help indentify LP numbers in the the request and will be needed for x1206 for 8 strip tube printing later on

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#770]
* Cytassist operation to have a dropdown list (LP1-LP20).
* One number per labware.

**Comment by KatyTudor** [comment]
@khelwood is it possible to get this information on the Cytassist view? sorry I realise its not on the story

**Comment by khelwood** [comment]
> [@khelwood](https://github.com/khelwood) is it possible to get this information on the Cytassist view? sorry I realise its not on the story

@KatyTudor It already is in the cytassist view on UAT.

**Comment by KatyTudor** [comment]
@khelwood sorry so it is, clearly wasn't looking properly this morning, sorry
