### ISSUE TITLE
x1254 AS (ARA) Jasmine I would to see the labware layout on the xenium anaylser page to help with region identification and naming and orientation

### ISSUE THREAD

**Issue by sabrine33** [sanger/stan-client#796]
before the barcode column in the labware table to see the section layout, but rotation 180 degree so the so A1 is at the bottom right.

**Comment by KatyTudor** [comment]
@khelwood @sabrine33 when did this go in to UAT for testing and then released? I wasn't aware of it being tested on on UAT, there are slight changes needed as the layout if possible needed to be by the bottom section for region of interest naming:

![Image](https://github.com/user-attachments/assets/b0181293-6cb7-4067-8c5c-4a9ed470fd3d)

**Comment by sabrine33** [comment]
Hi @KatyTudor, No problem, I can do that. However, there’s a slight issue: the table for the ROI might appear cumbersome. I suggest removing the barcode column, as the labware layout displayed next to it seems sufficient.

Are there any other columns you think could be removed? If not, that’s perfectly fine too.

**Comment by KatyTudor** [comment]
@sabrine33 thank you I think if we can the barcode on the layout that should be fine to remove from the column. 
that area is getting rather full isn't it but all the info there is needed unfortunately

**Comment by khelwood** [comment]
> @khelwood @sabrine33 when did this go in to UAT for testing and then released? I wasn't aware of it being tested on on UAT, there are slight changes needed as the layout if possible needed to be by the bottom section for region of interest naming:
> 
> ![Image](https://private-user-images.githubusercontent.com/111565178/393176862-b0181293-6cb7-4067-8c5c-4a9ed470fd3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0ODc5ODUsIm5iZiI6MTczMzQ4NzY4NSwicGF0aCI6Ii8xMTE1NjUxNzgvMzkzMTc2ODYyLWIwMTgxMjkzLTZjYjctNDA2Ny04YzVjLTRhOWVkNDcwZmQzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNlQxMjIxMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NmJiYjNlNTZhOTBjODFjZDY2NDY0NmVmMzU5NDRmNTU4Y2U2MWMxODFjOTQ5MGUzOGJiZTkyMWY1ZWNmMTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.F6SVR4XJKQ2jSPLyF773OPQ79xalRD8NBnAwNO7j0LY)

It looks like Sabrine closed the issue, which moves it to _Done_. I've reopened it.
