### ISSUE TITLE
x1262 client—As TS (Katy) I want to record section thickness to a precision of 0.5 for FFPE sectioning and actually record the thickness for HTA

### ISSUE THREAD

**Issue by khelwood** [sanger/stan-client#820]
Every request in the graphql that accepts a thickness is being changed from an int to a string.

**Comment by khelwood** [comment]
@sabrine33 ![Image](https://github.com/user-attachments/assets/c4a94c62-22bd-4726-89e3-35082300108a)

**Comment by sabrine33** [comment]
@khelwood, I will have a look, thanks
